### ISSUE TITLE
Broken with fluentd >= 0.14.4

### ISSUE THREAD

**Issue by jimmidyson** [kazegusuri/fluent-plugin-prometheus#10]
This [commit](https://github.com/fluent/fluentd/commit/29e41a24932f80ad7fa50be37b9633a36cdc1597) moved `MonitorAgentInput` to `Fluent::Plugin` & so this plugin is broken with fluentd >= 0.14.4.

The error message is `unexpected error error="uninitialized constant Fluent::MonitorAgentInput"`

**Comment by kazegusuri** [comment]
Thank you dor reporting. I will fix it this weekend.

**Comment by kazegusuri** [comment]
Fixed and released new version 0.2.1. Please try it again.
I also found an issue for fluentd self about MonitorAgentInput. It produces metrics for buffered output plugins such as `buffer_queue_length` even if it is non-buffered output pulgin. I will report upstream about it.

**Comment by jimmidyson** [comment]
Brilliant thanks!
