### ISSUE TITLE
multiple buffer support

### ISSUE THREAD

**Issue by FUSAKLA** [kazegusuri/fluent-plugin-prometheus#12]
Hi, just curious if you are going to implement possible enhanced api for fluentd v0.14 
which should provide possibility to use monitor_agent to get data from multiple buffers according to
 #https://github.com/fluent/fluentd/issues/855

for example if you have in configuration (with [concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat) plugin)
```
<source>
  @type prometheus_monitor
</source>
...
<filter **>
        @type concat
        key message
        multiline_start_regexp /foo.bar/
        flush_interval 5
        stream_identity_key container_id
        timeout_label @OUT
</filter>
```

**this leads to error:**
```
2017-02-24 12:04:03 +0100 [error]: #0 NoMethodError in monitoring plugins key="buffer_queue_length" plugin=Fluent::Plugin::ConcatFilter error_class=NoMethodError error="undefined method `queue' for {}:Hash"
```

this is caused by 
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_monitor_agent.rb#L276

where @buffer is hash due to multiple buffer usage

I know this error is not fault of this plugin but just suggesting possible improvement

**Comment by kazegusuri** [comment]
Yes, I will support v0.14 features, but don't have time for that for a while.
If this plugin is broken with current feature, I will fix asap.
Anyway, patches are welcome always.

**Comment by kazegusuri** [comment]
This issue is caused by fluentd itself. I fixed the issue in https://github.com/fluent/fluentd/pull/1556.
Please use Fluentd v0.14.16 or later to resolve this issue.

**Comment by FUSAKLA** [comment]
Ok great we already switched to 0.14 version.
Thanks for looking into this.
