### ISSUE TITLE
prometheus_monitor not updating metrics

### ISSUE THREAD

**Issue by glbyers** [kazegusuri/fluent-plugin-prometheus#13]
Currently testing fluentd-0.12.33 with fluent-plugin-prometheus-0.2.1 & prometheus-client-0.6.0 in a Kubernetes cluster. I don't believe metrics are being set in update_monitor_info. All requests to the scrape URL only ever returns the TYPE & HELP entries, but never any actual metrics (see below). I have the following minimal fluentd config;

```
  <source>
    @type prometheus
  </source>
  <source>
    @type prometheus_monitor
  </source>
```

```
curl http://xxx.xxx.xxx.xxx:24231/metrics/         
# TYPE fluentd_status_buffer_queue_length gauge
# HELP fluentd_status_buffer_queue_length Current buffer queue length.
# TYPE fluentd_status_buffer_total_bytes gauge
# HELP fluentd_status_buffer_total_bytes Current total size of queued buffers.
# TYPE fluentd_status_retry_count gauge
# HELP fluentd_status_retry_count Current retry counts.
 ```

Where do I start debugging this?

Thanks,
Grant

**Comment by glbyers** [comment]
Scratch that. Of course it won't work if I have no buffer plugins...

**Comment by anupamkamal01** [comment]
Facing similar issue. Can u pls help me out.
