### ISSUE TITLE
warn on filter parameters

### ISSUE THREAD

**Issue by prabhakm** [kazegusuri/fluent-plugin-prometheus#24]
Problem 1:
After taking a close look and reading the plugin doc in this github, there is one more problem -> the logs are not even seen on http://localhost:24231/metrics

So, I am guessing the source is also not working

curl http://localhost:24231/metrics does not show anything.

Problem 2:

I am following the steps as per this blog ->
https://blog.treasuredata.com/blog/2016/07/19/routing-data-from-docker-to-prometheus-server-via-fluentd/

The entire filter tag seems to be going as warn and not used. can please help
2017-05-13 19:40:31 -0400 [warn]: parameter 'type' in <filter **>
  type prometheus
  <metric>
    name test
    type counter
    desc total count
  </metric>
</filter> is not used.
2017-05-13 19:40:31 -0400 [warn]: parameter 'name' in <metric>
  name test
  type counter
  desc total count
</metric> is not used.
2017-05-13 19:40:31 -0400 [warn]: parameter 'type' in <metric>
  name test
  type counter
  desc total count
</metric> is not used.
2017-05-13 19:40:31 -0400 [warn]: parameter 'desc' in <metric>
  name test
  type counter
  desc total count
</metric> is not used.

**Comment by kazegusuri** [comment]
Can you paste your fluentd.conf and describe fluent-plugin-prometheus version?

**Comment by kazegusuri** [comment]
I close this issue because not updated.
Please feel free to reopen if you have a update or comment.
